name: Build npm release - $(Build.BuildId)

trigger:
  - master

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    variables:
      ESY__PREFIX: $(Pipeline.Workspace)/.esy
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/build-npm-packages.yml
    - template: .ci/build-docs.yml

  - job: macOS
    pool:
      vmImage: macOS-latest
    variables:
      ESY__PREFIX: $(Pipeline.Workspace)/.esy
    steps:
    - template: .ci/build-platform.yml
      parameters:
        esyLockPath: $(Build.SourcesDirectory)/esy.lock/index.json
        installFolderPath: /3_______________________________________________

  # - job: Windows
  #   pool:
  #     vmImage: windows-latest
  #   variables:
  #     ESY__PREFIX: $(Pipeline.Workspace)\.esy
  #   steps:
  #   - template: .ci/build-platform.yml
  #     parameters:
  #       esyLockPath: $(Build.SourcesDirectory)\esy.lock\index.json
  #       installFolderPath: \3_

- stage: Publish_docs
  displayName: Publish documentation
  dependsOn: [Build]
  jobs:
  - deployment: Publish_docs
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish docs to Github
    environment: gh-pages
    pool:
      vmImage: ubuntu-16.04
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                git clone https://$(github_pat)@github.com/reason-native-web/morph .
                git checkout gh-pages
                git pull
              workingDirectory: $(Build.StagingDirectory)
              displayName: "Clone GitHub pages repo"

            - script: |
                rm -rf $(Build.StagingDirectory)/morph || true
                rm -rf $(Build.StagingDirectory)/morph_client || true
                rm -rf $(Build.StagingDirectory)/morph_core || true
                rm $(Build.StagingDirectory)/index.html || true
                rm $(Build.StagingDirectory)/odoc.css || true
                rm $(Build.StagingDirectory)/highlight.pack.js || true
              displayName: Remove last version of the docs

            - task: DownloadPipelineArtifact@2
              displayName: Download docs
              inputs:
                artifactName: Docs
                targetPath: $(Build.StagingDirectory)
              
            - script: |
                git config user.name "Strid Bot"
                git add --all
                git commit --message "$(Build.SourceVersionMessage)"
                git push origin gh-pages
              workingDirectory: $(Build.StagingDirectory)
              displayName: "Push docs to Github pages"
