name: Build master - $(Build.BuildId)

trigger:
  - master

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    variables:
      ESY__PREFIX: $(Pipeline.Workspace)/.esy
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/build-npm-packages.yml
    - template: .ci/build-docs.yml

  - job: macOS
    pool:
      vmImage: macOS-latest
    variables:
      ESY__PREFIX: $(Pipeline.Workspace)/.esy
    steps:
    - template: .ci/build-platform.yml
      parameters:
        esyLockPath: $(Build.SourcesDirectory)/esy.lock/index.json
        installFolderPath: /3_______________________________________________

  # - job: Windows
  #   pool:
  #     vmImage: windows-latest
  #   variables:
  #     ESY__PREFIX: $(Pipeline.Workspace)\.esy
  #   steps:
  #   - template: .ci/build-platform.yml
  #     parameters:
  #       esyLockPath: $(Build.SourcesDirectory)\esy.lock\index.json
  #       installFolderPath: \3_

- stage: Publish_docs
  displayName: Publish documentation
  dependsOn: [Build]
  jobs:
  - deployment: Publish_docs
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish docs to Github
    environment: gh-pages
    pool:
      vmImage: ubuntu-16.04
    strategy:
      runOnce:
        deploy:
          steps:
            - template: .ci/publish-api-docs.yml
  - deployment: Upstream_docs
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Upstream docs to reason-native-web.github.io
    environment: reason-native-web_github_io
    pool:
      vmImage: ubuntu-16.04
    strategy:
      runOnce:
        deploy:
          steps:
            - template: .ci/upstream-docs.yml
